# Generated by Django 2.2 on 2021-08-12 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import spplitAccount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('username', models.CharField(max_length=30, verbose_name='유저명')),
                ('phone', models.CharField(max_length=30, verbose_name='번호')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스태프 권한')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용중')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입일')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', spplitAccount.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category1', models.CharField(default='All', editable=False, max_length=30)),
                ('is_checked_category1', models.BooleanField(default=True, editable=False)),
                ('category2', models.CharField(default='Bookmark', editable=False, max_length=30)),
                ('is_checked_category2', models.BooleanField(default=True, editable=False)),
                ('category3', models.CharField(default='Work', editable=False, max_length=30)),
                ('is_checked_category3', models.BooleanField(blank=True, default=True, null=True)),
                ('category4', models.CharField(default='Group', editable=False, max_length=30)),
                ('is_checked_category4', models.BooleanField(blank=True, default=True, null=True)),
                ('category5', models.CharField(default='Sports', editable=False, max_length=30)),
                ('is_checked_category5', models.BooleanField(blank=True, default=False, null=True)),
                ('category6', models.CharField(default='Hobby', editable=False, max_length=30)),
                ('is_checked_category6', models.BooleanField(blank=True, default=False, null=True)),
                ('category7', models.CharField(default='Others', editable=False, max_length=30)),
                ('is_checked_category7', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='division_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '카테고리목록',
                'verbose_name_plural': '카테고리목록',
                'db_table': 'Division_table',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category1', models.CharField(default='All', editable=False, max_length=30)),
                ('category2', models.CharField(default='Bookmark', editable=False, max_length=30)),
                ('category3', models.CharField(default='Work', max_length=30)),
                ('category4', models.CharField(default='Teams', max_length=30)),
                ('category5', models.CharField(blank=True, max_length=30, null=True)),
                ('category6', models.CharField(blank=True, max_length=30, null=True)),
                ('category7', models.CharField(blank=True, max_length=30, null=True)),
                ('category8', models.CharField(blank=True, max_length=30, null=True)),
                ('category9', models.CharField(blank=True, max_length=30, null=True)),
                ('category10', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cateogory_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'db_table': 'Category_table',
            },
        ),
    ]
